apiVersion: v1
kind: Service
metadata:
  namespace: muxisite
  labels:
    run: muxisite-auth-api
  name: muxisite-auth-api
spec:
  ports:
  - port: 5499
    targetPort: 5499
    protocol: TCP
  selector:
    run: muxisite-auth-api
