apiVersion: v1
kind: Service
metadata:
  namespace: muxisite
  labels:
    run: muxisite_auth_api
  name: muxisite_auth_api
spec:
  ports:
  - port: 5499
    targetPort: 5499
    protocol: TCP
  selector:
    run: muxisite_auth_api
