apiVersion: v1
kind: Service
metadata:
  namespace: xueer
  labels:
    run: xueer-fe
  name: xueer-fe
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    run: xueer-fe
